spring.application.name=StatLineGuessr

# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/statlineguessr
spring.datasource.username=statline_user
spring.datasource.password=statline_pass

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Serialize LocalDate/LocalDateTime as ISO strings, not timestamps
spring.jackson.serialization.write-dates-as-timestamps=false

# Server
server.port=8080
